# git aliases
alias gp='git push'
alias gpo='git push origin'
alias gpom='git push origin master'
alias gl='git pull'
alias glo='git pull origin'
alias gck='git checkout'
alias gst='git status'
alias gco='git commit'
alias gdf='git diff'
alias grb='git rebase'
alias grbc='git rebase --continue'
alias grbs='git rebase --skip'
alias gad='git add .'
